name: quiche_vpn
description: A lightweight VPN
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.0.0
  pretty_dio_logger: ^1.1.1
  dartz: ^0.10.1
  retrofit: ^4.0.1
  connectivity_plus: ^3.0.2
  # State management
  provider: ^6.0.5
  # User interface
  flutter_svg: ^2.0.1
  card_swiper: ^2.0.4
  # Annotation
  json_annotation: ^4.8.0
  # Language
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  json_serializable: ^6.5.4
  retrofit_generator: ^5.0.0
  build_runner: ^2.3.2
  build_web_compilers: ^3.2.7
  mockito: ^5.3.2
  analyzer: ^5.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/locales/

  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Exo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo2-Regular.ttf
          weight: 400